// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pr07webapi.Data;

#nullable disable

namespace Pr07webapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002182047_BookData")]
    partial class BookData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pr07webapi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Michael Bay",
                            Title = "Transformers",
                            Year = 2007
                        },
                        new
                        {
                            Id = 2,
                            Author = "F. Scott Fitzgerald",
                            Title = "The Great Gatsby",
                            Year = 1925
                        },
                        new
                        {
                            Id = 3,
                            Author = "Harper Lee",
                            Title = "To Kill a Mockingbird",
                            Year = 1960
                        },
                        new
                        {
                            Id = 4,
                            Author = "George Orwell",
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.K. Rowling",
                            Title = "Harry Potter and the Sorcerer's Stone",
                            Year = 1997
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.R.R. Tolkien",
                            Title = "The Hobbit",
                            Year = 1937
                        },
                        new
                        {
                            Id = 7,
                            Author = "Jane Austen",
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.D. Salinger",
                            Title = "The Catcher in the Rye",
                            Year = 1951
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.R.R. Tolkien",
                            Title = "The Lord of the Rings",
                            Year = 1954
                        },
                        new
                        {
                            Id = 10,
                            Author = "George Orwell",
                            Title = "Animal Farm",
                            Year = 1945
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
